name: venv
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.10=h7a1cb2a_2
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pytorch=2.1.2  
  - torchvision=0.16.2 
  - cudatoolkit=11.8 
  - pip:
      - accelerate==1.10.1
      - aiosignal==1.4.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gdown==5.2.0
      - hf-xet==1.1.10
      - higher==0.2.1
      - holidays==0.64
      - huggingface-hub==0.35.3
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - networkx==3.4.2
      - numpy==1.26.3
      - packaging==25.0
      - pandas==2.3.3
      - patsy==1.0.1
      - peft==0.17.1
      - pillow==11.3.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - protobuf==6.32.1
      - psutil==7.1.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytorch-wavelets==1.3.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - ray==2.10.0
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - seaborn==0.13.2
      - six==1.17.0
      - soupsieve==2.8
      - statsmodels==0.14.4
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.52.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - torch-dct==0.1.6
      - autoflake==2.3.1
      - timm==1.0.20